enable
configure
no filter-map ipv4 INTERNET_IN 5
filter-map ipv4 INTERNET_IN 5
 match gre host 172.16.2.5 host 172.16.1.4
 set crypto-map VPN-MAP peer 172.16.1.4
exit
no filter-map ipv4 INTERNET_IN 10
filter-map ipv4 INTERNET_IN 10
 match udp host 172.16.1.4 eq 4500 host 172.16.2.5 eq 4500
 set crypto-map VPN-MAP peer 172.16.1.4
exit
no filter-map ipv4 INTERNET_IN 20
filter-map ipv4 INTERNET_IN 20
 match tcp any any ack
 set accept
exit
no filter-map ipv4 INTERNET_IN 30
filter-map ipv4 INTERNET_IN 30
 match tcp any any eq 22
 match tcp any any eq 53
 match tcp any any eq 80
 match tcp any any eq 443
 match tcp any any eq 8080
 match tcp any any eq 2026
 set accept
exit
no filter-map ipv4 INTERNET_IN 40
filter-map ipv4 INTERNET_IN 40
 match udp any any eq 53
 match udp any eq 53 192.168.3.0/28
 set accept
exit
no filter-map ipv4 INTERNET_IN 50
filter-map ipv4 INTERNET_IN 50
 match udp any any eq 123
 match udp any eq 123 192.168.3.0/28
 set accept
exit
no filter-map ipv4 INTERNET_IN 60
filter-map ipv4 INTERNET_IN 60
 match icmp any any
 set accept
exit
interface int0
 set filter-map in INTERNET_IN 20
 set filter-map in INTERNET_IN 30
 set filter-map in INTERNET_IN 40
 set filter-map in INTERNET_IN 50
 set filter-map in INTERNET_IN 60
 set filter-map in INTERNET_IN 5
 set filter-map in INTERNET_IN 10
 no set filter-map in VPN-FILTER 10
exit
end
write memory
