enable
configure
no filter-map ipv4 INTERNET_IN 5
no filter-map ipv4 INTERNET_IN 15
no filter-map ipv4 INTERNET_IN 10
filter-map ipv4 INTERNET_IN 10
 match tcp any any ack
 match tcp any eq 53 192.168.1.0/27
 match tcp any eq 53 192.168.2.0/28
 match tcp any eq 80 192.168.1.0/27
 match tcp any eq 80 192.168.2.0/28
 match tcp any eq 443 192.168.1.0/27
 match tcp any eq 443 192.168.2.0/28
 set accept
exit
no filter-map ipv4 INTERNET_IN 20
filter-map ipv4 INTERNET_IN 20
 match tcp any any eq 22
 match tcp any any eq 8080
 match tcp any any eq 2026
 set accept
exit
no filter-map ipv4 INTERNET_IN 30
filter-map ipv4 INTERNET_IN 30
 match udp any eq 53 192.168.1.0/27
 match udp any eq 53 192.168.2.0/28
 set accept
exit
no filter-map ipv4 INTERNET_IN 40
filter-map ipv4 INTERNET_IN 40
 match udp any eq 123 192.168.1.0/27
 match udp any eq 123 192.168.2.0/28
 set accept
exit
no filter-map ipv4 INTERNET_IN 50
filter-map ipv4 INTERNET_IN 50
 match udp any any eq 500
 set accept
exit
no filter-map ipv4 INTERNET_IN 60
filter-map ipv4 INTERNET_IN 60
 match icmp any any
 set accept
exit
interface int0
 set filter-map in VPN-FILTER 5
 set filter-map in VPN-FILTER 10
 no set filter-map in VPN-FILTER 15
 set filter-map in INTERNET_IN 10
 set filter-map in INTERNET_IN 20
 set filter-map in INTERNET_IN 30
 set filter-map in INTERNET_IN 40
 set filter-map in INTERNET_IN 50
 set filter-map in INTERNET_IN 60
exit
end
write memory
