enable
configure
crypto-ipsec ike enable
crypto-ipsec profile VPN ike-v2
 mode tunnel
 ike-phase1
  proposal aes256-sha256-modp2048
  auth pre-shared-key P@ssw0rd
 exit
 ike-phase2
  protocol esp
  proposal aes256-sha256
  local-ts 172.16.1.4
  remote-ts 172.16.2.5
 exit
exit
crypto-map VPN-MAP 10
 match peer 172.16.2.5
 set crypto-ipsec profile VPN
exit
filter-map ipv4 VPN-FILTER 5
 match gre host 172.16.1.4 host 172.16.2.5
 set crypto-map VPN-MAP peer 172.16.2.5
exit
no filter-map ipv4 VPN-FILTER 10
filter-map ipv4 VPN-FILTER 10
 match udp host 172.16.2.5 eq 500 host 172.16.1.4 eq 500
 match udp host 172.16.2.5 eq 4500 host 172.16.1.4 eq 4500
 set crypto-map VPN-MAP peer 172.16.2.5
exit
filter-map ipv4 VPN-FILTER 15
 match any any any
 set accept
exit
interface int0
 set filter-map in VPN-FILTER 10
exit
interface tunnel.0
 no set filter-map in VPN-FILTER 10
exit
end
write memory
